version = 1

[[annotations]]
path = [
    "Tests/SpeziQuestionnaireTests/Resources/**"
]
SPDX-FileCopyrightText = "2026 Stanford University and the project authors (see CONTRIBUTORS.md)"
SPDX-License-Identifier = "MIT"