#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  buildandtest:
    name: Build and Test Swift Package
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      artifactname: SpeziQuestionnaire.xcresult
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziQuestionnaire
  buildandtestvisionos:
    name: Build and Test Swift Package visionOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      artifactname: SpeziQuestionnaire-visionOS.xcresult
      resultBundle: SpeziQuestionnaire-visionOS.xcresult
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziQuestionnaire
      destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
  buildandtestuitests:
    name: Build and Test UI Tests
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      artifactname: TestApp.xcresult
      runsonlabels: '["macOS", "self-hosted"]'
      path: 'Tests/UITests'
      scheme: TestApp
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [buildandtest, buildandtestvisionos, buildandtestuitests]
    uses: StanfordSpezi/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: SpeziQuestionnaire.xcresult SpeziQuestionnaire-visionOS.xcresult TestApp.xcresult
